version: 2.1
orbs:
  mapi: forallsecure/mapi@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1

filters: &filters
  tags:
    only: /.*/

jobs:
  # Create a job to test the commands of your orbs.
  # You may want to add additional validation steps to ensure the commands are working as expected.
  command-tests:
    machine:
      image: ubuntu-2204:2022.07.1
    steps:
      - checkout
      # Run your orb's commands to validate them.
      - mapi/scan:
          api-url: "https://demo-api.mayhem.security/api/v3"
          api-spec: "https://demo-api.mayhem.security/api/v3/openapi.json"
          target: "forallsecure/integrations/mapi-circleci-orb"
          duration: "10sec"
          sarif-report: "/tmp/mapi/report.sarif"
          run-args: |
            # Basic Auth
            --basic-auth
            login:password
            # Treat all warnings as errors
            --warnaserror
      - store_artifacts:
          path: /tmp/mapi
      - store_test_results:
          path: /tmp/mapi/junit.xml
workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - command-tests:
          context: orb-publishing
          filters: *filters
      # test mapi scan job
      - mapi/scan:
          context: orb-publishing
          api-url: "https://demo-api.mayhem.security/api/v3"
          api-spec: "https://demo-api.mayhem.security/api/v3/openapi.json"
          target: "forallsecure/integrations/mapi-circleci-orb"
          duration: "10sec"
          zap-api-scan: true
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: forallsecure/mapi
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - command-tests
            - mapi/scan
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
